import json, pathlib, collections
path=pathlib.Path('/mnt/data/work135/questions.json')
q=json.load(open(path,encoding='utf-8'))
ids={x['id'] for x in q}
new=[
{
'id':'add20260531_problem_001','category':'情報社会の問題解決','difficulty':'basic','question':'学校の遅刻者数が増えている原因を調べるとき、問題解決の進め方として最も適切なものはどれか。','choices':['最初に思いついた対策をすぐ全校に実施する。','現状をデータで把握し、仮説を立てて原因を検討する。','遅刻した生徒だけを叱れば、原因の分析は不要である。','前年の資料は使わず、印象だけで判断する。'],'answer':1,'explanation':'問題解決では、まず現状をデータで把握し、原因について仮説を立て、対策を考えて効果を確認する流れが大切である。'},
{
'id':'add20260531_problem_002','category':'情報社会の問題解決','difficulty':'standard','question':'アンケート結果をもとに校内の自習スペースを改善する。分析で注意すべきこととして最も適切なものはどれか。','choices':['回答者の人数や属性に偏りがないかを確認する。','最も目立つ自由記述だけを根拠に決定する。','割合ではなく回答数だけを見れば十分である。','都合のよい回答を選べば客観的な分析になる。'],'answer':0,'explanation':'アンケートは、回答数や回答者の属性に偏りがあると結果の解釈を誤ることがある。割合や母集団、質問文の影響も確認する。'},
{
'id':'add20260531_problem_003','category':'情報社会の問題解決','difficulty':'advanced','question':'購買の混雑を減らすため、昼休み前半と後半で利用者数を記録した。改善案の効果を判断する方法として最も適切なものはどれか。','choices':['改善案を実施した日の感想だけで判断する。','実施前後で同じ条件のデータを集め、混雑時間や待ち時間を比較する。','利用者が少ない日だけを選んで効果があったと判断する。','売上金額だけを見れば混雑の変化も必ず分かる。'],'answer':1,'explanation':'対策の効果を判断するには、実施前後でできるだけ同じ条件のデータを集め、待ち時間や利用者数など目的に合う指標で比較する。'},
{
'id':'add20260531_netdata_001','category':'情報通信ネットワークとデータ','difficulty':'basic','question':'Webページを閲覧するとき、URLのドメイン名からIPアドレスを調べる仕組みとして最も適切なものはどれか。','choices':['DNS','SMTP','USB','GPU'],'answer':0,'explanation':'DNSは、ドメイン名とIPアドレスを対応付ける仕組みである。Webページへのアクセスでは、まずドメイン名からIPアドレスを調べる。'},
{
'id':'add20260531_netdata_002','category':'情報通信ネットワークとデータ','difficulty':'standard','question':'同じファイルを送るとき、通信速度が速くなると一般にどうなるか。','choices':['送信に必要な時間は長くなる。','送信に必要な時間は短くなる。','ファイルサイズが必ず大きくなる。','IPアドレスが使えなくなる。'],'answer':1,'explanation':'通信時間は、おおまかにデータ量を通信速度で割って求める。通信速度が速くなれば、同じデータ量を送る時間は短くなる。'},
{
'id':'add20260531_netdata_003','category':'情報通信ネットワークとデータ','difficulty':'standard','question':'HTTPSでWebサイトに接続する主な目的として最も適切なものはどれか。','choices':['画面の色を自動で見やすくするため。','通信内容の盗聴や改ざんを防ぎやすくするため。','画像の解像度を必ず高くするため。','サーバを使わずに通信するため。'],'answer':1,'explanation':'HTTPSはHTTPにTLSなどによる暗号化と認証の仕組みを加えたもので、通信内容の盗聴や改ざんを防ぎやすくする。'},
{
'id':'add20260531_netdata_004','category':'情報通信ネットワークとデータ','difficulty':'advanced','question':'100Mバイトのファイルを、実効速度20Mビット/秒の回線で送る。およその送信時間として最も近いものはどれか。ただし1バイト＝8ビットとする。','choices':['4秒','20秒','40秒','400秒'],'answer':2,'explanation':'100Mバイトは800Mビットである。800Mビット ÷ 20Mビット/秒 = 40秒となる。単位をバイトからビットに直す点に注意する。'},
{
'id':'add20260531_oscpu_001','category':'OS・CPU・プログラム','difficulty':'basic','question':'OSの役割として最も適切なものはどれか。','choices':['アプリケーションや周辺機器を管理し、コンピュータを使いやすくする。','CPUの中にある演算回路だけを指す。','写真の画素数を必ず増やす。','インターネット上の住所を表す番号である。'],'answer':0,'explanation':'OSは、ファイル、メモリ、入出力装置、アプリケーションの実行などを管理し、利用者がコンピュータを扱いやすくする基本ソフトウェアである。'},
{
'id':'add20260531_oscpu_002','category':'OS・CPU・プログラム','difficulty':'standard','question':'CPUの「制御装置」の説明として最も適切なものはどれか。','choices':['命令を解釈し、各装置へ動作の指示を出す。','長期間データを保存する装置である。','画面に画像を表示するための外部装置である。','無線でデータを送受信する規格である。'],'answer':0,'explanation':'CPUの制御装置は、主記憶から取り出した命令を解釈し、演算装置や主記憶などに必要な動作を指示する。'},
{
'id':'add20260531_oscpu_003','category':'OS・CPU・プログラム','difficulty':'advanced','question':'主記憶装置と補助記憶装置の説明として最も適切なものはどれか。','choices':['主記憶装置はCPUが直接利用しやすいが、電源を切ると内容が失われることが多い。','補助記憶装置はCPUの中にあり、計算だけを担当する。','主記憶装置はデータを長期間保存するためだけに使われ、実行中のプログラムは置かれない。','補助記憶装置はキーボードやマウスだけを指す。'],'answer':0,'explanation':'主記憶装置は実行中のプログラムやデータを置くために使われ、CPUから高速に利用される。一方、補助記憶装置は電源を切ってもデータを保存する用途に使われる。'},
{
'id':'add20260531_prog_001','category':'コンピュータとプログラミング','difficulty':'basic','question':'プログラムにおける「変数」の説明として最も適切なものはどれか。','choices':['値に名前を付けて一時的に保存するためのもの。','画面の明るさを調整する部品。','インターネット上の住所を表す番号。','ファイルを圧縮するためだけの記号。'],'answer':0,'explanation':'変数は、数値や文字列などの値を一時的に保存し、後から参照したり更新したりするために使う。'},
{
'id':'add20260531_prog_002','category':'コンピュータとプログラミング','difficulty':'standard','question':'条件分岐を使う場面として最も適切なものはどれか。','choices':['点数が80点以上なら「合格」、それ以外なら「再確認」と表示する。','同じ処理を必ず100回繰り返す。','データを保存せずに必ず消去する。','プログラムの説明文だけを印刷する。'],'answer':0,'explanation':'条件分岐は、条件が成り立つかどうかによって処理を変える仕組みである。「80点以上なら」のような判断に使う。'},
{
'id':'add20260531_prog_003','category':'コンピュータとプログラミング','difficulty':'advanced','question':'配列 scores = [60, 75, 90] の各要素に5を足して表示する処理として最も適切な考え方はどれか。','choices':['配列の要素を順に取り出し、それぞれに5を加える。','配列名を5に変更すれば、すべての要素に5が足される。','最初の要素だけに5を足せば、残りも自動で変わる。','配列は数値を扱えないので処理できない。'],'answer':0,'explanation':'配列の複数の要素に同じ処理を行うときは、繰り返しを使って要素を順に取り出し、それぞれに処理を行う。'},
{
'id':'add20260531_design_fig_001','category':'情報デザイン','difficulty':'standard','question':'次の画面案で、入力ミスを減らすための改善として最も適切なものはどれか。','figureSvg':'<svg viewBox="0 0 560 260" role="img" aria-label="申込フォームの画面案"><rect x="40" y="35" width="480" height="190" rx="16" fill="#ffffff" stroke="#334155" stroke-width="2"/><text x="280" y="68" text-anchor="middle" class="label">申込フォーム</text><text x="80" y="108" class="caption">電話番号</text><rect x="170" y="88" width="250" height="34" rx="6" fill="#f8fafc" stroke="#94a3b8"/><text x="180" y="111" class="caption">例：0258123456</text><text x="80" y="156" class="caption">希望日</text><rect x="170" y="136" width="250" height="34" rx="6" fill="#f8fafc" stroke="#94a3b8"/><text x="180" y="159" class="caption">2026/6/10</text><rect x="350" y="184" width="90" height="30" rx="8" fill="#dbeafe" stroke="#2563eb"/><text x="395" y="204" text-anchor="middle" class="caption">送信</text></svg>','choices':['電話番号や日付の入力例、形式の説明を表示する。','入力欄をすべて同じ名前にする。','送信ボタンを画面外に置く。','入力エラーがあっても利用者に知らせない。'],'answer':0,'explanation':'入力ミスを減らすには、入力例や形式、エラー表示などを分かりやすく示すことが有効である。利用者が迷わず入力できる設計が重要である。'},
{
'id':'add20260531_data_fig_001','category':'データの活用','difficulty':'standard','question':'次の度数分布表から読み取れることとして最も適切なものはどれか。','figureSvg':'<svg viewBox="0 0 560 300" role="img" aria-label="小テストの点数の度数分布表"><rect x="80" y="55" width="400" height="190" fill="#ffffff" stroke="#334155" stroke-width="2"/><line x1="80" y1="95" x2="480" y2="95" stroke="#334155"/><line x1="260" y1="55" x2="260" y2="245" stroke="#334155"/><text x="170" y="82" text-anchor="middle" class="label">点数</text><text x="370" y="82" text-anchor="middle" class="label">人数</text><text x="170" y="125" text-anchor="middle" class="caption">0〜39</text><text x="370" y="125" text-anchor="middle" class="caption">2</text><text x="170" y="160" text-anchor="middle" class="caption">40〜59</text><text x="370" y="160" text-anchor="middle" class="caption">6</text><text x="170" y="195" text-anchor="middle" class="caption">60〜79</text><text x="370" y="195" text-anchor="middle" class="caption">14</text><text x="170" y="230" text-anchor="middle" class="caption">80〜100</text><text x="370" y="230" text-anchor="middle" class="caption">8</text></svg>','choices':['最も人数が多い階級は60〜79点である。','80〜100点の人数が最も少ない。','40点未満の人数は6人である。','全員が60点以上である。'],'answer':0,'explanation':'各階級の人数は、0〜39点が2人、40〜59点が6人、60〜79点が14人、80〜100点が8人である。最も多いのは60〜79点である。'},
{
'id':'add20260531_network_fig_001','category':'情報通信ネットワーク','difficulty':'advanced','question':'次の図のように、PCからWebサーバへアクセスする。家庭内LANの機器Aとして最も適切なものはどれか。','figureSvg':'<svg viewBox="0 0 640 250" role="img" aria-label="PCからルータを通ってインターネット上のWebサーバへ接続する図"><rect x="45" y="95" width="110" height="58" rx="10" fill="#e0f2fe" stroke="#0369a1"/><text x="100" y="130" text-anchor="middle" class="label">PC</text><rect x="255" y="90" width="125" height="68" rx="12" fill="#fef3c7" stroke="#92400e"/><text x="317" y="118" text-anchor="middle" class="label">機器A</text><text x="317" y="142" text-anchor="middle" class="caption">LANと外部を接続</text><ellipse cx="485" cy="124" rx="80" ry="45" fill="#dcfce7" stroke="#166534"/><text x="485" y="129" text-anchor="middle" class="label">インターネット</text><rect x="540" y="170" width="80" height="42" rx="8" fill="#f8fafc" stroke="#334155"/><text x="580" y="196" text-anchor="middle" class="caption">Webサーバ</text><path d="M155 124 L255 124" stroke="#2563eb" stroke-width="4" marker-end="url(#a1)"/><path d="M380 124 L405 124" stroke="#2563eb" stroke-width="4" marker-end="url(#a1)"/><path d="M520 154 L560 170" stroke="#2563eb" stroke-width="4" marker-end="url(#a1)"/><defs><marker id="a1" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#2563eb"/></marker></defs></svg>','choices':['ルータ','プリンタ','スキャナ','表計算ソフト'],'answer':0,'explanation':'家庭内LANとインターネットなど外部ネットワークを接続し、通信の経路を選ぶ機器はルータである。'},
{
'id':'add20260531_security_001','category':'情報セキュリティ','difficulty':'basic','question':'フィッシングの説明として最も適切なものはどれか。','choices':['本物に似せたメールやサイトで、IDやパスワードを入力させようとする手口。','コンピュータの処理速度を上げるための部品。','画像を小さくして保存容量を減らす方法。','正規のソフトウェア更新だけを行う仕組み。'],'answer':0,'explanation':'フィッシングは、銀行やサービスを装ったメールや偽サイトなどで利用者をだまし、ID、パスワード、クレジットカード情報などを入力させる手口である。'},
{
'id':'add20260531_security_002','category':'情報セキュリティ','difficulty':'standard','question':'多要素認証を用いる利点として最も適切なものはどれか。','choices':['パスワード以外の要素も確認するため、不正ログインを防ぎやすくなる。','パスワードを全員で共有しやすくなる。','暗号化を使わなくても通信内容が完全に安全になる。','利用者を確認せずにログインできるようになる。'],'answer':0,'explanation':'多要素認証は、知識情報（パスワードなど）、所持情報（スマートフォンなど）、生体情報など複数の要素を組み合わせて本人確認を強化する。'},
{
'id':'add20260531_digital_001','category':'コンピュータとデジタル表現','difficulty':'standard','question':'白黒画像を横100画素、縦100画素、1画素1ビットで保存する。画像データ量として最も適切なものはどれか。','choices':['100ビット','1,000ビット','10,000ビット','100,000ビット'],'answer':2,'explanation':'画素数は100×100=10,000画素である。1画素1ビットなので、画像データ量は10,000ビットとなる。'},
{
'id':'add20260531_digital_002','category':'コンピュータとデジタル表現','difficulty':'advanced','question':'音声を1秒間に44,100回標本化し、1回あたり16ビット、2チャンネルで10秒間記録する。データ量として最も近いものはどれか。','choices':['約88kビット','約1.4Mビット','約14Mビット','約141Mビット'],'answer':2,'explanation':'44,100回/秒 × 16ビット × 2チャンネル × 10秒 = 14,112,000ビットで、約14Mビットである。'},
{
'id':'add20260531_ip_001','category':'知的財産権','difficulty':'standard','question':'著作物を授業で利用するときの考え方として最も適切なものはどれか。','choices':['どのような場合でも、出典を示せば無断で自由に公開できる。','授業目的でも、利用範囲や公開範囲、引用の条件などを確認する必要がある。','インターネット上の画像はすべて著作権がない。','有名でない作品には著作権が発生しない。'],'answer':1,'explanation':'授業での利用には一定の例外が認められる場合があるが、範囲や条件がある。公開や配布の方法、引用の要件、出典表示などを確認することが大切である。'},
{
'id':'add20260531_algo_fig_001','category':'アルゴリズムとプログラミング','difficulty':'advanced','question':'次の流れで、n=5 のとき最後に表示される値はどれか。','figureSvg':'<svg viewBox="0 0 520 360" role="img" aria-label="nから1までの和を求めるフローチャート"><rect x="210" y="25" width="100" height="36" rx="18" fill="#dcfce7" stroke="#166534"/><text x="260" y="49" text-anchor="middle" class="label">開始</text><rect x="170" y="82" width="180" height="42" rx="8" fill="#e0f2fe" stroke="#0369a1"/><text x="260" y="109" text-anchor="middle" class="caption">sum=0, i=1</text><polygon points="260,145 360,190 260,235 160,190" fill="#fef3c7" stroke="#92400e" stroke-width="2"/><text x="260" y="195" text-anchor="middle" class="caption">i≦n?</text><rect x="170" y="255" width="180" height="42" rx="8" fill="#e0f2fe" stroke="#0369a1"/><text x="260" y="282" text-anchor="middle" class="caption">sum=sum+i, i=i+1</text><rect x="395" y="170" width="90" height="40" rx="8" fill="#fee2e2" stroke="#991b1b"/><text x="440" y="196" text-anchor="middle" class="caption">sum表示</text><path d="M260 61 L260 82" stroke="#334155" stroke-width="3" marker-end="url(#af)"/><path d="M260 124 L260 145" stroke="#334155" stroke-width="3" marker-end="url(#af)"/><path d="M260 235 L260 255" stroke="#334155" stroke-width="3" marker-end="url(#af)"/><path d="M170 276 L115 276 L115 190 L160 190" fill="none" stroke="#334155" stroke-width="3" marker-end="url(#af)"/><path d="M360 190 L395 190" stroke="#334155" stroke-width="3" marker-end="url(#af)"/><text x="284" y="250" class="caption">はい</text><text x="365" y="178" class="caption">いいえ</text><defs><marker id="af" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#334155"/></marker></defs></svg>','choices':['5','10','15','20'],'answer':2,'explanation':'iが1から5までの間、sumにiを足す。1+2+3+4+5=15なので、最後に表示される値は15である。'}
]
for item in new:
    assert item['id'] not in ids, item['id']
    assert len(item['choices'])==4
q.extend(new)
path.write_text(json.dumps(q,ensure_ascii=False,indent=2),encoding='utf-8')
js=pathlib.Path('/mnt/data/work135/data/questions.js')
js.write_text('const QUESTIONS = '+json.dumps(q,ensure_ascii=False,indent=2)+';\n',encoding='utf-8')
print('added',len(new),'total',len(q))
print(collections.Counter(x['category'] for x in q))
